name: Swift CI

on:
  push:
    branches:
      - Develope
  pull_request:
    branches:
      - Develope

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Check Swift version
        run: swift --version

      - name: Build Project
        run: swift build --package-path SwiftErrorArchiver/

      - name: Run Tests
        run: swift test --package-path SwiftErrorArchiver/
