name: Swift CI

on:
  push:
    branches:
      - Develope
  pull_request:
    branches:
      - Develope

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: SwiftyLab/setup-swift@latest

      - name: Get swift version
        run: swift --version
      
      - name: Get Tree
        run: tree .

      - name: Build and Test Project
        run: |
          cd SwiftErrorArchiver
          swift build
          swift test
