name: Swift CI

on:
  push:
    branches:
      - Develope
  pull_request:
    branches:
      - Develope

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            swift: "5"
          - os: macos-latest
            swift: "5"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        if: ${{ matrix.os == 'macos-latest' }}
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install Swift
        uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}

      - name: Check Swift version
        run: swift --version

      - name: Build Project
        run: swift build --package-path SwiftErrorArchiver/

      - name: Run Tests
        run: swift test --package-path SwiftErrorArchiver/
