name: Swift

on:
  push:
    branches:
      - Develope
  pull_request:
    branches:
      - Develope

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["6.0", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2.1.0
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --package-path SwiftErrorArchiver/ 
      - name: Run tests
        run: swift test --package-path SwiftErrorArchiver/ 