name: Swift CI

on:
  push:
    branches:
      - Develope
  pull_request:
    branches:
      - Develope

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # Swift 환경 설정
      - uses: SwiftyLab/setup-swift@latest

      # Swift 버전 확인
      - name: Get Swift version
        run: swift --version

      # Build 및 Test 실행
      - name: Build and Test Project
        run: |
          cd SwiftErrorArchiver
          swift build --package-path SwiftErrorArchiver/
          swift test --package-path SwiftErrorArchiver/
